### ISSUE TITLE
[Enhancement] Support Higher Encryption like SHA256

### ISSUE THREAD

**Issue by ferventcoder** [ferventcoder/checksum#1]
- [x] SHA256
- [x] SHA512

**Comment by jberezanski** [comment]
How about switching from [explicitly creating the various hash algorithm implementations](https://github.com/ferventcoder/checksum/blob/master/src/checksum/Program.cs#L30-L35) to the [HashAlgorithm.Create() method](https://msdn.microsoft.com/en-us/library/wet69s13(v=vs.100).aspx)? You could pass `configuration.HashType` directly to the method, gaining automatic support for all current and future hashes supported by .NET.

**Comment by ferventcoder** [comment]
Already looking at doing that - evolutionary design. :)

**Comment by ferventcoder** [comment]
@stefanscherer over here

**Comment by StefanScherer** [comment]
@ferventcoder Thanks. Haven't done any C# yet and trying to "connect the dots". As it seems the suggestion with `HashAlgorithm.Create()` seems the right way to do it.

**Comment by ferventcoder** [comment]
Yep. The current solution here is a very YAGNI implementation. Adding in another type necessitates the need for refactoring. :)

**Comment by dragon788** [comment]
@ferventcoder I've noticed some packages using sha256 now, is this already implemented?

**Comment by ferventcoder** [comment]
Yes. Forgot to close this. Thanks for the reminder.

**Comment by ferventcoder** [comment]
https://github.com/ferventcoder/checksum/commit/c212eb102179a512087ccf371c505ac8e1b9632a
